<template>
  <div>
    <BsTable :items='items' :fields='fields' :perPage='perPage' :pageOptions='pageOptions' />
  </div>
</template>

<script>
import BsTable from '@/global/table/BsTable.vue'

export default {
  components: {
    BsTable,
  },
  data() {
    return {
      perPage: 5,
      pageOptions: [5, 10, 15],
      filter: null,
      fields: [
        { key: "twoPartNameWithUserName", label: "نام", sortable: true },
        { key: "email", label: "ایمیل", sortable: true },
        { key: "userName", label: "نام کاربری" , sortable: true},
        { key: "branch", label: "شعبه", sortable: true },
        { key: "type", label: "نوع", sortable: true },
        { key: "actionsMerchantsListUsers", label: "عملیات" },
      ],
      items: [
        {
          id:1,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'آقای',
          lastName:'حسینی',
          email: "hosseini@elanusclub.com",
          userName: "09123456789",
          branch: "تعریف نشده",
          type: "مدیر",
        },
        {
          id:12,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'سمانه',
          lastName:'بهمنی',
          email: "s.bahmani@elanusclub.com",
          userName: "09123456789",
          branch: "تعریف نشده",
          type: "مدیر",
        },
        {
          id:13,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'مدیر',
          lastName:'سیستم',
          email: "admin@elanusclub.com",
          userName: "09123456789",
          branch: "تعریف نشده",
          type: "مدیر",
        },
        {
          id:14,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'مهدی',
          lastName:'بیات',
          email: "m.bayat@elanusclub.com",
          userName: "09123456789",
          branch: "تعریف نشده",
          type: "مدیر",
        },
        {
          id:15,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'آقای',
          lastName:'حسینی',
          email: "hosseini@elanusclub.com",
          userName: "09123456789",
          branch: "تعریف نشده",
          type: "مدیر",
        },
        {
          id:16,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'سمانه',
          lastName:'بهمنی',
          email: "s.bahmani@elanusclub.com",
          userName: "09123456789",
          branch: "تعریف نشده",
          type: "مدیر",
        },
        {
          id:17,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'مدیر',
          lastName:'سیستم',
          email: "admin@elanusclub.com",
          userName: "09123456789",
          branch: "تعریف نشده",
          type: "مدیر",
        },
        {
          id:18,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'مهدی',
          lastName:'بیات',
          email: "m.bayat@elanusclub.com",
          userName: "09123456789",
          branch: "تعریف نشده",
          type: "مدیر",
        },
        {
          id:19,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'آقای',
          lastName:'حسینی',
          email: "hosseini@elanusclub.com",
          userName: "09123456789",
          branch: "تعریف نشده",
          type: "مدیر",
        },
        {
          id:10,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'سمانه',
          lastName:'بهمنی',
          email: "s.bahmani@elanusclub.com",
          userName: "09123456789",
          branch: "تعریف نشده",
          type: "مدیر",
        },
        {
          id:11,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'مدیر',
          lastName:'سیستم',
          email: "admin@elanusclub.com",
          userName: "09123456789",
          branch: "تعریف نشده",
          type: "مدیر",
        },
        {
          id:111,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'مهدی',
          lastName:'بیات',
          email: "m.bayat@elanusclub.com",
          userName: "09123456789",
          branch: "تعریف نشده",
          type: "مدیر",
        },
        {
          id:112,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'آقای',
          lastName:'حسینی',
          email: "hosseini@elanusclub.com",
          userName: "09123456789",
          branch: "تعریف نشده",
          type: "مدیر",
        },
        {
          id:113,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'سمانه',
          lastName:'بهمنی',
          email: "s.bahmani@elanusclub.com",
          userName: "09123456789",
          branch: "تعریف نشده",
          type: "مدیر",
        },
        {
          id:114,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'مدیر',
          lastName:'سیستم',
          email: "admin@elanusclub.com",
          userName: "09123456789",
          branch: "تعریف نشده",
          type: "مدیر",
        },
        {
          id:115,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'مهدی',
          lastName:'بیات',
          email: "m.bayat@elanusclub.com",
          userName: "09123456789",
          branch: "تعریف نشده",
          type: "مدیر",
        },
        {
          id:116,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'مدیر',
          lastName:'سیستم',
          email: "admin@elanusclub.com",
          userName: "user-admin",
          branch: "تعریف نشده",
          type: "مدیر",
        },
        {
          id:117,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'مهدی',
          lastName:'بیات',
          email: "m.bayat@elanusclub.com",
          userName: "09123456789",
          branch: "تعریف نشده",
          type: "مدیر",
        },
        {
          id:118,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'آقای',
          lastName:'حسینی',
          email: "hosseini@elanusclub.com",
          userName: "09123456789",
          branch: "تعریف نشده",
          type: "مدیر",
        },
        {
          id:119,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'سمانه',
          lastName:'بهمنی',
          email: "s.bahmani@elanusclub.com",
          userName: "09123456789",
          branch: "تعریف نشده",
          type: "مدیر",
        },
        {
          id:120,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'مدیر',
          lastName:'سیستم',
          email: "admin@elanusclub.com",
          userName: "09123456789",
          branch: "تعریف نشده",
          type: "مدیر",
        },
        {
          id:121,
          avatarIcon: "MonitorIcon",
          avatarColor: "light-primary",
          firstName:'مهدی',
          lastName:'بیات',
          email: "m.bayat@elanusclub.com",
          userName: "09123456789",
          branch: "تعریف نشده",
          type: "مدیر",
        },
      ],
    };
  },
};
</script>
